# Generated by Django 6.0.1 on 2026-02-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_profile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
