# Generated by Django 6.0.1 on 2026-02-02 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_profile_adresse_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par 0 et contenir exactement 10 chiffres', regex='^0\\d{9}$')]),
        ),
    ]
