# Generated by Django 6.0.1 on 2026-02-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_profile_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='montant',
        ),
    ]
