# Generated by Django 6.0.1 on 2026-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_remove_profile_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
