# Generated by Django 6.0.1 on 2026-02-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_profile_solde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='solde',
        ),
    ]
