# Generated by Django 6.0.1 on 2026-02-10 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_remove_profile_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number must start with 0 and contain exactly 10 digits.', regex='^0\\d{9}$')]),
        ),
    ]
