# Generated by Django 6.0.1 on 2026-02-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
