# Generated by Django 6.0.1 on 2026-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
