# Generated by Django 6.0.1 on 2026-03-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_profile_use_2fa'),
        ('root', '0020_paiement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='root.category'),
        ),
    ]
