# Generated by Django 6.0.1 on 2026-04-05 11:13

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_profile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
