# Generated by Django 6.0.1 on 2026-04-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_profile_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='totp_secret',
        ),
    ]
