# Generated by Django 6.0.1 on 2026-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_remove_profile_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
