# Generated by Django 6.0.1 on 2026-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0017_profile_totp_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='use_2fa',
            new_name='use_2fa_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='use_2fa_totp',
            field=models.BooleanField(default=True),
        ),
    ]
