# Generated by Django 6.0.1 on 2026-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0018_rename_use_2fa_profile_use_2fa_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='use_2fa_totp',
            field=models.BooleanField(default=False),
        ),
    ]
