# Generated by Django 6.0.1 on 2026-02-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepurchase',
            name='activation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.activationcode'),
        ),
    ]
