# Generated by Django 6.0.1 on 2026-02-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_codepurchase_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepurchase',
            name='activation_code',
        ),
        migrations.AlterField(
            model_name='codepurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='root.product'),
        ),
        migrations.CreateModel(
            name='PurchaseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='root.activationcode')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='root.codepurchase')),
            ],
        ),
    ]
