# Generated by Django 6.0.1 on 2026-02-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_category_active_alter_subcategory_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
