# Generated by Django 6.0.1 on 2026-02-10 09:23

import django.utils.timezone
import root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_remove_codepurchase_activation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchasecode',
            name='codePur',
            field=models.CharField(default=root.models.generate_code, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='purchasecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasecode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
