# Generated by Django 6.0.1 on 2026-02-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_remove_category_slug_remove_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
