# Generated by Django 6.0.1 on 2026-02-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_alter_profile_phone'),
        ('root', '0004_purchasecode_active_purchasecode_codepur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodePurchase',
            new_name='ProductAchat',
        ),
    ]
