# Generated by Django 6.0.1 on 2026-02-03 14:44

import root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='date_attribue',
        ),
        migrations.AddField(
            model_name='paiement',
            name='codeP',
            field=models.CharField(default=root.models.generate_code, max_length=100, unique=True),
        ),
    ]
