# Generated by Django 6.0.1 on 2026-02-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_rename_codepurchase_productachat'),
    ]

    operations = [
        migrations.AddField(
            model_name='productachat',
            name='reste_after_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
