# Generated by Django 6.0.1 on 2026-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_productachat_reste_after_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type_category',
            field=models.CharField(choices=[('request', 'Request'), ('code', 'Code')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productachat',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
