# Generated by Django 6.0.1 on 2026-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_category_type_category_productachat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productachat',
            name='requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
