# Generated by Django 6.0.1 on 2026-02-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.activationcode')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='root.paiement')),
            ],
        ),
    ]
