# Generated by Django 6.0.1 on 2026-02-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_codepurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodePurchase',
        ),
    ]
