# Generated by Django 6.0.1 on 2026-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_productachat_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='productachat',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
