# Generated by Django 6.0.1 on 2026-02-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_productachat_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productachat',
            name='requirement',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
