# Generated by Django 6.0.1 on 2026-02-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_remove_profile_solde'),
        ('root', '0009_delete_codepurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.activationcode')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_purchases', to='authentification.profile')),
            ],
        ),
    ]
