# Generated by Django 6.0.1 on 2026-02-05 08:57

import root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_codepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepurchase',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codepurchase',
            name='codeCP',
            field=models.CharField(default=root.models.generate_code, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='codepurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
