# Generated by Django 6.0.1 on 2026-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_productachat_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productachat',
            name='requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
