# Generated by Django 6.0.1 on 2026-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_alter_productachat_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('request', 'Request'), ('code', 'Code')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
