# Generated by Django 6.0.1 on 2026-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_category',
            field=models.CharField(choices=[('request', 'Request'), ('code', 'Code'), ('ibo', 'Ibo')], max_length=20),
        ),
    ]
