# Generated by Django 6.0.1 on 2026-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_alter_category_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productachat',
            name='type_vie',
            field=models.CharField(blank=True, choices=[('1_year', '1 Year'), ('lifetime', 'Lifetime')], max_length=20, null=True),
        ),
    ]
