# Generated by Django 6.0.1 on 2026-03-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_productachat_type_vie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productachat',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='root.product'),
        ),
    ]
