# Generated by Django 6.0.1 on 2026-03-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_alter_productachat_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productachat',
            name='type_vie',
        ),
    ]
