# Generated by Django 6.0.1 on 2026-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_remove_productachat_type_vie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_category',
            field=models.CharField(choices=[('request', 'Request'), ('code', 'Code')], max_length=20),
        ),
    ]
