# Generated by Django 6.0.1 on 2026-03-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_alter_category_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('payment', 'Paiement'), ('refund', 'Remboursement')], default='payment', max_length=20),
        ),
    ]
