# Generated by Django 6.0.1 on 2026-03-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_activationcodelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationcodelog',
            name='product_id',
        ),
        migrations.AddField(
            model_name='activationcodelog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.product'),
        ),
    ]
