# Generated by Django 6.0.1 on 2026-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_remove_activationcodelog_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcodelog',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationcodelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
