# Generated by Django 6.0.1 on 2026-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_activationcodelog_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.IntegerField(),
        ),
    ]
