# Generated by Django 6.0.1 on 2026-03-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_alter_paiement_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productachat',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
