# Generated by Django 6.0.1 on 2026-03-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_alter_productachat_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productachat',
            name='reste_after_purchase',
            field=models.IntegerField(),
        ),
    ]
