# Generated by Django 6.0.1 on 2026-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0027_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='code_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
