# Generated by Django 6.0.1 on 2026-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_activationcode_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
