# Generated by Django 6.0.1 on 2026-04-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0029_alter_activationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.TextField(),
        ),
    ]
