# Generated by Django 6.0.1 on 2026-04-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0030_alter_activationcode_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activationcode',
            unique_together={('product', 'code_hash')},
        ),
    ]
