# Generated by Django 6.0.1 on 2026-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_alter_activationcode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('debite', 'Debited'), ('credite', 'Credited'), ('refund', 'Remboursement')], default='credite', max_length=20),
        ),
    ]
