# Generated by Django 6.0.1 on 2026-04-08 13:48

import root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_alter_paiement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='code_activ',
            field=models.CharField(default=root.models.generate_unique_code, max_length=100, unique=True),
        ),
    ]
