# Generated by Django 6.0.1 on 2026-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_alter_activationcode_code_activ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='code_activ',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
