# Generated by Django 6.0.1 on 2026-04-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0034_alter_activationcode_code_activ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='codeP',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
