# Generated by Django 6.0.1 on 2026-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_alter_paiement_codep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='codeN',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
